libraray_arg:
  max_poly   :  6
  max_dt     :  1
  max_dx     :  6
  use_cross_der : False

Noise:
  sigma_SNR  :  0.1
  
Subsampling:
  stride_x    : 5
  stride_t    : 3

Dataset_name:
  equation   : 'Nonlinear Schrodinger (NLS) (2 variables 1D)'
  filename   : 'NLS.npy'

Other_paramters:
  Tau        : 0.05