libraray_arg:
  max_poly   :  6
  max_dt     :  1
  max_dx     :  6
  use_cross_der : False

Noise:
  sigma_SNR  :  0.2
  
Subsampling:
  stride_x    : 4
  stride_t    : 12

Dataset_name:
  equation   : 'Korteweg-de Vires (KdV) Equation (1 variables, 1D)'
  filename   : 'KdV.npy'

Other_paramters:
  Tau        : 0.05