libraray_arg:
  max_poly   :  6
  max_dt     :  1
  max_dx     :  6
  use_cross_der : False
  
Noise:
  sigma_SNR  :  0.5
  
Subsampling:
  stride_x    : 5
  stride_t    : 6

Dataset_name:
  equation    : 'Transport Equation'
  filename   : 'transportDiff.npy'

Other_paramters:
  Tau        : 0.05
