libraray_arg:
  max_poly   :  4
  max_dt     :  1
  max_dx     :  0
  use_cross_der : False

Noise:
  sigma_SNR  :  0.1
  
Subsampling:
  stride_x    : 5
  stride_t    : 5

Dataset_name:
  equation    : 'Lotka Volterra Equation (2 variables, 2D)'
  filename    : 'LotkaVolterra2D2.npy'

Other_paramters:
  Tau            : 0.05